#########mysql数据库配置###########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

############freemarker配置##########
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: /ftl/  #默认路径classpath:/templates/
    # prefix:
       # suffix:.ftl
##############jsp配置###############
  mvc:
     view:
       prefix: /WEB-INF/jsp/
       suffix: .jsp

################server############
server:
  port: 80
  #context-path: /jack
  tomcat:
    uri-encoding: utf-8
########pageHelper配置############
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
cat:
  id: 12
  name: 狗蛋-test
  age: 250







